; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3]
platform = espressif32@6.9.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM=0
	-DUSER_SETUP_LOADED=1
	-DGC9A01_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=240
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=10
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=3
	-DSPI_FREQUENCY=80000000
	-DSPI_READ_FREQUENCY=20000000
	-DLOAD_GLCD=0
	-DLOAD_FONT2=0
	-DLOAD_FONT4=0
	-DLOAD_GFXFF=0
	-DSMOOTH_FONT=0
	-DLV_CONF_INCLUDE_SIMPLE=1
	-I src
    -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src
    -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFiClientSecure/src
	-DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
	-DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
	-DCONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
	-DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
	-DCONFIG_BT_NIMBLE_MAX_BONDS=1
	-DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=128
	-DCONFIG_BT_NIMBLE_MAX_CCCDS=4
	-DCONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME="HuonyxWatch"
	-DCONFIG_NIMBLE_CPP_ENABLE_RETURN_CODE_TEXT=0
	-DCONFIG_NIMBLE_CPP_ENABLE_GAP_EVENT_CODE_TEXT=0
	-DCONFIG_NIMBLE_CPP_ENABLE_ADVERTISEMENT_TYPE_TEXT=0
	-Os
	-ffunction-sections
	-fdata-sections
	-DCORE_DEBUG_LEVEL=0
build_unflags = -Wl,--no-gc-sections
extra_linker_flags = -Wl,--gc-sections
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^7.2.1
	links2004/WebSockets@^2.6.1
	h2zero/NimBLE-Arduino@^2.1.1
	lvgl/lvgl@9.2.0
lib_ldf_mode = deep+
lib_compat_mode = off
